# build environment
FROM node:19.0.0-alpine as build
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json

ARG VITE_APP_API_URL="https://jurapro.bhuser.ru/api-shop"
RUN echo "VITE_APP_API_URL=${VUE_APP_API_URL}" > .env


RUN npm install --silent
COPY . /app
RUN npm run build


# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]